services:
  mariadb:
    container_name: web-mariadb-14
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 14_Calculator
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "0.0.0.0:5054:3306"

  web:
    container_name: 14_Calculator
    hostname: app
    build: .
    ports:
      - "0.0.0.0:5014:5014"