services:
  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - ./prometheus/data:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - metrics-net

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 9000:8081
    networks:
      - metrics-net

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
      - renderer
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana:rw
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:9000/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - metrics-net

networks:
  metrics-net:
    name: metrics-net