global:
  scrape_interval: 10s

rule_files:
  - "/etc/prometheus/config/rules.yml"

scrape_configs:
  - job_name: "14_web-metrics-api"
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ["93.88.178.186:5014"]
