version: "3.9"

services:
  db:
    image: postgres:16
    container_name: steel_db
    restart: always
    environment:
      POSTGRES_USER: steel_user
      POSTGRES_PASSWORD: steel_pass
      POSTGRES_DB: steel_db
    ports:
      - "5054:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U steel_user"]
      interval: 5s
      timeout: 3s
      retries: 8

  web:
    build: .
    container_name: steel_app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
    - ./steel_predict_project:/app

    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data:
