version: "3.9"

services:
  db:
    image: postgres:16
    container_name: steel_db
    restart: always
    environment:
      POSTGRES_USER: steel_user
      POSTGRES_PASSWORD: steel_pass
      POSTGRES_DB: steel_db
    ports:
      - "5054:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: steel_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  jenkins:
    image: jenkins/jenkins:lts
    container_name: steel_jenkins
    user: root
    restart: always
    ports:
      - "5014:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  postgres_data:
  jenkins_home:
